void fatal(char *fmt, ...);
int yyerror(char *fmt, ...);
void shell_text(char *);
void pushsrc(int, char *);
void definition(char *);
char *delimstr(char *);
void undefine(char *);
void dodef(struct symtab *);
int dwb_input(void);
int unput(int);
void pbstr(char *);
double errcheck(double, char *);
void copyfile(char *);
void copydef(struct symtab *p);
struct symtab *copythru(char *);
void copyuntil(char *);
void copy(void);
void shell_init(void);
void shell_exec(void);
