void freenode(obj *);
double getcomp(obj *, int);
int exprsave(double);
char *sprintgen(char *);
void printexpr(double);
void printpos(obj *);
char *tostring(char *);
obj *makepos(double, double, int, obj *);
obj *makebetween(double, obj *, obj *);
obj *getnth(obj *, int);
obj *getpos(obj *, int);
int whatpos(obj *, int, float *, float *);
obj *gethere(void);
obj *getlast(int, int);
obj *getfirst(int, int);
double getblkvar(obj *, char *);
obj *fixpos(obj *, double, double);
obj *addpos(obj *, obj *);
obj *subpos(obj *, obj *);
obj *makenode(int, int, int);
void extreme(double, double, float *);
void track_bounds(double, double, double, double);
void get_bounds(obj *, float *, int);
void get_tot_bounds(obj *, float *, int);
int transformed(obj *);
