#
#

all:	ansi-eqn
	./unansi ansi-eqn unansi-eqn
	./merge ansi-eqn unansi-eqn kr-eqn
	@echo Compile and test the eqn source in kr-eqn

ansi-eqn:
	@echo "Create the directory $@ and copy your source in it"

