void getdraw(void);
void drawline(int, int);
void drawcirc(int);
void drawarc(int, int, int, int, int);
void drawspline(FILE *, int);
void beginpath(char *, int);
void drawpath(char *, int);
void newbaseline(char *);
void drawtext(char *);
void settext(char *);
void drawellip(int, int);
