.TH SUBJ 1
.SH NAME
.B subj
\- generate a list of subjects from a document
.SH SYNOPSIS
\*(mBsubj\f1
.OP "" files []
.SH DESCRIPTION
.B subj
searches
.I files
for subjects
that might be appropriate in a subject-page index and 
prints the list of subjects on the standard output.
The document  
should contain formatting commands (from
.BR nroff ,
.BR troff ,
and
.SM MM
among others)
to make the best
use of
.BR subj .
.SH WARNINGS
.B subj
selects sequences of capitalized words as subjects except the first
word in each sentence.
Thus, if a sentence begins with a proper noun, the capitalization rule
will not select this word as a subject.
On the other hand, since each sentence is expected to begin on a
newline, the first word of a sentence that begins in the middle of a line
may be erroneously selected.
.PP
The output of
.B subj
may not be appropriate for your needs and
should be edited accordingly.
.SH BUGS
.B subj
also selects as subjects modifier-noun sequences from the abstract, headings,
and topic sentences (the first sentence in each paragraph),
and occasionally a word is incorrectly
categorized as a noun or adjective.
.SH SEE ALSO
.BR mm (1),
.BR mmt (1),
.BR ndx (1),
.BR nroff (1),
.BR troff (1)
